task:
  name: Android Build
  only_if: $CIRRUS_BRANCH !=~ 'release/.*'
  env:
    ENCRYPT_KEY: ENCRYPTED[c49306f16bf1ded621f7c7289fff76a52233586e5f2c3a9be212d51fd79a99d2a8f4ddab781d6aaa5d56ddb84a1e91b7]
  osx_instance:
    image: catalina-flutter
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - openssl aes-256-cbc -d -in android/keystore.properties.encrypted -k ${ENCRYPT_KEY} >> android/keystore.properties
    - openssl aes-256-cbc -d -in android/service_account.json.encrypted -k ${ENCRYPT_KEY} >> android/service_account.json
    - openssl aes-256-cbc -d -in android/app/google-services.json.encrypted -k ${ENCRYPT_KEY} >> android/app/google-services.json
    - openssl aes-256-cbc -d -in android/app/elainedbdev.encrypted -k ${ENCRYPT_KEY} >> android/app/elainedbdev
    - flutter build appbundle
    - cd android
    - bundle exec fastlane supply --aab ../build/app/outputs/bundle/release/app-release.aab

task:
  name: iOS Build
  only_if: $CIRRUS_BRANCH !=~ 'release/.*'
  env:
    ENCRYPT_KEY: ENCRYPTED[c49306f16bf1ded621f7c7289fff76a52233586e5f2c3a9be212d51fd79a99d2a8f4ddab781d6aaa5d56ddb84a1e91b7]
    FASTLANE_USER: "elainedb.dev@gmail.com"
    FASTLANE_PASSWORD: ENCRYPTED[c31e6f4125d7264c0161ce1036f149d47d19b2650b7dcb5954ad61d50ffa79ae1c742762cfb3b7862c17d2201d01e23f]
    FASTLANE_SESSION: ENCRYPTED[23b1b41ccb4425f1e3d8f9517f622b82a848a49786d6aeff8ebf17780e8b6f0b36b93fe004ebc61b814b5ae265459adb]
    FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ENCRYPTED[c605aabe9ffd2015db445297921e56c91524392dbf74d38c9592b1417c948f2f5f796440a977d6e36d47a80e722ef0aa]
    GIT_AUTH: ENCRYPTED[3a1e29b5ea91aa50aa86d96b3555b10d8f54b3fb650cbf0576224ebdaf9fd53cc8ccedffd27d5f45287a1097dc94180c]
    MATCH_PASSWORD: ENCRYPTED[83f9c7fb44e17242e16042cd94b0eae771e4b09aaa1fb373f4a263fb1a11ff1338b5f31cd3246461408730414d33156a]
  osx_instance:
    image: catalina-flutter
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - openssl aes-256-cbc -d -in ios/Runner/GoogleService-Info.plist.encrypted -k ${ENCRYPT_KEY} >> ios/Runner/GoogleService-Info.plist
    - flutter build ios --release --no-codesign
    - cd ios
    - export MATCH_GIT_BASIC_AUTHORIZATION="$(echo -n ${GIT_AUTH} | base64)"
    - bundle exec fastlane beta