name: registry_helper_for_wu
description: Registry Helper for Wizards Unite

# buildName+buildNumber
# Android: buildName = versionName / buildNumber = versionCode
# iOS: buildName = CFBundleShortVersionString / buildNumber = CFBundleVersion
version: 1.5.4+16

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  charts_flutter: ^0.8.1
  cloud_firestore: ^0.12.10+2
  firebase_analytics: ^5.0.6
  firebase_auth: ^0.15.0+1
  firebase_core: ^0.4.1+5
  firebase_crashlytics: ^0.1.1+2
  firebase_performance: ^0.3.1+4
  google_sign_in: ^4.0.14
  package_info: ^0.4.0+10
  quick_actions: ^0.3.3+1
  scroll_to_index: ^1.0.4+1
  share: ^0.6.3+1
  shared_preferences: ^0.5.4+5
  shimmer: ^1.0.1
  tutorial_coach_mark:
    git:
      url: https://github.com/Vanethos/tutorial_coach_mark.git
      ref: TCM_6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/foundables/
    - assets/images/foundables/3.0x/
    - assets/images/traces/
    - assets/images/traces_transparent/
    - assets/json/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700