name: registry_helper_for_wu
description: Registry Helper for Wizards Unite

# buildName+buildNumber
# Android: buildName = versionName / buildNumber = versionCode
# iOS: buildName = CFBundleShortVersionString / buildNumber = CFBundleVersion
version: 1.4.4+8

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.4
  firebase_core: ^0.4.0
  firebase_auth: ^0.11.1+8
  cloud_firestore: ^0.12.7
  shared_preferences: ^0.5.3+4
  scroll_to_index: any
  package_info: ^0.4.0+3
  charts_flutter: ^0.6.0
  firebase_crashlytics: ^0.0.4+11
  firebase_analytics: ^4.0.2
  quick_actions: ^0.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/foundables/
    - images/foundables/3.0x/
    - images/traces/
    - images/traces_transparent/
    - json/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
