name: registry_helper_for_wu
description: Registry Helper for Wizards Unite

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# buildName+buildNumber
# Android: buildName = versionName / buildNumber = versionCode
# iOS: buildName = CFBundleShortVersionString / buildNumber = CFBundleVersion
version: 2.0.0+32

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  charts_flutter: ^0.9.0
  cloud_firestore: ^0.14.1+3
  firebase_analytics: ^6.0.2
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  firebase_crashlytics: ^0.2.1+1
  firebase_performance: ^0.4.0+2
  google_sign_in: ^4.5.5
  apple_sign_in: ^0.1.0

  device_info: ^0.4.2+9
  package_info: ^0.4.3
  quick_actions: ^0.4.0+10
  scroll_to_index: ^1.0.6
  share: ^0.6.5+3
  shared_preferences: ^0.5.12+2
  shimmer: ^1.1.2
  tutorial_coach_mark:
    git:
      url: https://github.com/Vanethos/tutorial_coach_mark.git
      ref: TCM_6
  mobx: ^1.2.1+3
  flutter_mobx: ^1.1.0+2
  get_it: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  mobx_codegen: ^1.1.1+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/buttons/
    - assets/images/buttons/3.0x/ # https://appleid.cdn-apple.com/appleid/button?border_radius=50&height=48&color=white&scale=3&locale=fr_FR&width=200
    - assets/images/icons/
    - assets/images/foundables/
    - assets/images/foundables/3.0x/
    - assets/images/traces/
    - assets/images/traces_transparent/
    - assets/json/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700