# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    lane :retrieve_fastlane_session do
        # runs shell
        spaceauth_output = `bundle exec fastlane spaceauth`
        # regex the output for the value we need
        fastlane_session_regex = %r{Pass the following via the FASTLANE_SESSION environment variable:\n(?<session>.+)\n\n\nExample:\n.+}
        new_session = nil
        if match = spaceauth_output.match(fastlane_session_regex)
            # Strip out the fancy formatting
            new_session = match[:session].gsub("\e[4m\e[36m", "").gsub("\e[0m\e[0m", "")
        end

        # Yell and quit if unable to parse out session from spaceauth output
        if new_session.nil?
            puts "Unable to obtain new session via fastlane spaceauth"
        exit 1
        else
            run environment_variable FASTLANE_SESSION:new_session
        end
    end

    desc "Push a new beta build to TestFlight"
    lane :beta do
        # build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
        match
        build_ios_app(export_xcargs: "-allowProvisioningUpdates", export_method: "app-store")
        upload_to_testflight
    end
end
